"""Initial database migration

Revision ID: 227afa020c6e
Revises: 
Create Date: 2024-11-29 14:31:24.655724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '227afa020c6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('album_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_title', sa.String(length=255), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('cover_art', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('album_title IS NOT NULL', name='album_title_not_null'),
    sa.CheckConstraint('release_date IS NOT NULL', name='release_date_not_null'),
    sa.PrimaryKeyConstraint('album_id')
    )
    op.create_index('idx_albums_title', 'albums', ['album_title'], unique=False)
    op.create_index(op.f('ix_albums_album_id'), 'albums', ['album_id'], unique=False)
    op.create_table('artists',
    sa.Column('artist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('artist_bio', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('artist_id'),
    sa.UniqueConstraint('artist_name')
    )
    op.create_index('idx_artists_name', 'artists', ['artist_name'], unique=False)
    op.create_index(op.f('ix_artists_artist_id'), 'artists', ['artist_id'], unique=False)
    op.create_table('genres',
    sa.Column('genre_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('genre_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('genre_id'),
    sa.UniqueConstraint('genre_name')
    )
    op.create_index('idx_genres_name', 'genres', ['genre_name'], unique=False)
    op.create_index(op.f('ix_genres_genre_id'), 'genres', ['genre_id'], unique=False)
    op.create_table('media',
    sa.Column('media_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_title', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.Enum('AUDIO', 'VIDEO', name='mediatypeenum'), nullable=False),
    sa.Column('duration', sa.Time(), nullable=True),
    sa.Column('s3_media_path', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_image_path', sa.String(length=255), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_premium_only', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('media_id'),
    sa.UniqueConstraint('media_title')
    )
    op.create_index('idx_media_title', 'media', ['media_title'], unique=False)
    op.create_index('idx_media_type', 'media', ['media_type'], unique=False)
    op.create_index('idx_media_view_count', 'media', ['view_count'], unique=False)
    op.create_index(op.f('ix_media_media_id'), 'media', ['media_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('album_artists',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'artist_id')
    )
    op.create_index('idx_album_artists_album_id', 'album_artists', ['album_id'], unique=False)
    op.create_index('idx_album_artists_artist_id', 'album_artists', ['artist_id'], unique=False)
    op.create_table('media_albums',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.album_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'media_id')
    )
    op.create_index('idx_media_albums_media_id', 'media_albums', ['media_id'], unique=False)
    op.create_table('media_artists',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'artist_id')
    )
    op.create_index('idx_media_artists_artist_id', 'media_artists', ['artist_id'], unique=False)
    op.create_index('idx_media_artists_media_id', 'media_artists', ['media_id'], unique=False)
    op.create_table('media_genres',
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.genre_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_id', 'genre_id')
    )
    op.create_index('idx_media_genres_genre_id', 'media_genres', ['genre_id'], unique=False)
    op.create_index('idx_media_genres_media_id', 'media_genres', ['media_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_role'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index('idx_comments_media_id', 'comments', ['media_id'], unique=False)
    op.create_index('idx_comments_user_id', 'comments', ['user_id'], unique=False)
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.create_table('favorites',
    sa.Column('favorite_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('favorite_id')
    )
    op.create_index('idx_favorites_media_id', 'favorites', ['media_id'], unique=False)
    op.create_index('idx_favorites_user_id', 'favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_favorites_favorite_id'), 'favorites', ['favorite_id'], unique=False)
    op.create_table('play_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('played_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index('idx_play_history_media_id', 'play_history', ['media_id'], unique=False)
    op.create_index('idx_play_history_played_at', 'play_history', ['played_at'], unique=False)
    op.create_index('idx_play_history_user_id', 'play_history', ['user_id'], unique=False)
    op.create_table('playlists',
    sa.Column('playlist_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('playlist_title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id')
    )
    op.create_index('idx_playlist_is_public', 'playlists', ['is_public'], unique=False)
    op.create_index('idx_playlist_user_id', 'playlists', ['user_id'], unique=False)
    op.create_index(op.f('ix_playlists_playlist_id'), 'playlists', ['playlist_id'], unique=False)
    op.create_table('ratings',
    sa.Column('rating_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='valid_rating_range'),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rating_id')
    )
    op.create_index('idx_ratings_media_id', 'ratings', ['media_id'], unique=False)
    op.create_index('idx_ratings_rating', 'ratings', ['rating'], unique=False)
    op.create_index('idx_ratings_user_id', 'ratings', ['user_id'], unique=False)
    op.create_index(op.f('ix_ratings_rating_id'), 'ratings', ['rating_id'], unique=False)
    op.create_table('user_artists',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.artist_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'artist_id')
    )
    op.create_index('idx_user_artist_artist_id', 'user_artists', ['artist_id'], unique=False)
    op.create_index('idx_user_artist_follower_id', 'user_artists', ['follower_id'], unique=False)
    op.create_table('playlist_media',
    sa.Column('playlist_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.media_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.playlist_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('playlist_id', 'media_id')
    )
    op.create_index('idx_playlist_media_media_id', 'playlist_media', ['media_id'], unique=False)
    op.create_index('idx_playlist_media_playlist_id', 'playlist_media', ['playlist_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_playlist_media_playlist_id', table_name='playlist_media')
    op.drop_index('idx_playlist_media_media_id', table_name='playlist_media')
    op.drop_table('playlist_media')
    op.drop_index('idx_user_artist_follower_id', table_name='user_artists')
    op.drop_index('idx_user_artist_artist_id', table_name='user_artists')
    op.drop_table('user_artists')
    op.drop_index(op.f('ix_ratings_rating_id'), table_name='ratings')
    op.drop_index('idx_ratings_user_id', table_name='ratings')
    op.drop_index('idx_ratings_rating', table_name='ratings')
    op.drop_index('idx_ratings_media_id', table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_playlists_playlist_id'), table_name='playlists')
    op.drop_index('idx_playlist_user_id', table_name='playlists')
    op.drop_index('idx_playlist_is_public', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('idx_play_history_user_id', table_name='play_history')
    op.drop_index('idx_play_history_played_at', table_name='play_history')
    op.drop_index('idx_play_history_media_id', table_name='play_history')
    op.drop_table('play_history')
    op.drop_index(op.f('ix_favorites_favorite_id'), table_name='favorites')
    op.drop_index('idx_favorites_user_id', table_name='favorites')
    op.drop_index('idx_favorites_media_id', table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.drop_index('idx_comments_user_id', table_name='comments')
    op.drop_index('idx_comments_media_id', table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_media_genres_media_id', table_name='media_genres')
    op.drop_index('idx_media_genres_genre_id', table_name='media_genres')
    op.drop_table('media_genres')
    op.drop_index('idx_media_artists_media_id', table_name='media_artists')
    op.drop_index('idx_media_artists_artist_id', table_name='media_artists')
    op.drop_table('media_artists')
    op.drop_index('idx_media_albums_media_id', table_name='media_albums')
    op.drop_table('media_albums')
    op.drop_index('idx_album_artists_artist_id', table_name='album_artists')
    op.drop_index('idx_album_artists_album_id', table_name='album_artists')
    op.drop_table('album_artists')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_media_media_id'), table_name='media')
    op.drop_index('idx_media_view_count', table_name='media')
    op.drop_index('idx_media_type', table_name='media')
    op.drop_index('idx_media_title', table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_genres_genre_id'), table_name='genres')
    op.drop_index('idx_genres_name', table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_artists_artist_id'), table_name='artists')
    op.drop_index('idx_artists_name', table_name='artists')
    op.drop_table('artists')
    op.drop_index(op.f('ix_albums_album_id'), table_name='albums')
    op.drop_index('idx_albums_title', table_name='albums')
    op.drop_table('albums')
    # ### end Alembic commands ###
